### ISSUE TITLE
HTTP 429 (rate limited) is being encountered when retrieving server member data

### ISSUE THREAD

**Issue by jonfelixrico** [jonfelixrico/wisdom-panel-server-2022#51]
Refer to the ff. logs

```
backend_1  | [Wisdom] Error     Sat, 14 Jan 2023 16:01:10 GMT [ExceptionsHandler] Request failed with status code 429 - {"stack":["AxiosError: Request failed with status code 429\n    at settle (/app/node_modules/.pnpm/axios@1.2.2/node_modules/axios/dist/node/axios.cjs:1859:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@1.2.2/node_modules/axios/dist/node/axios.cjs:2723:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]} +43sbackend_1  | [Wisdom] Error     Sat, 14 Jan 2023 16:01:10 GMT [ExceptionsHandler] Request failed with status code 429 - {"stack":["AxiosError: Request failed with status code 429\n    at settle (/app/node_modules/.pnpm/axios@1.2.2/node_modules/axios/dist/node/axios.cjs:1859:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@1.2.2/node_modules/axios/dist/node/axios.cjs:2723:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]} +39ms
backend_1  | [Wisdom] Error     Sat, 14 Jan 2023 16:01:10 GMT [ExceptionsHandler] Request failed with status code 429 - {"stack":["AxiosError: Request failed with status code 429\n    at settle (/app/node_modules/.pnpm/axios@1.2.2/node_modules/axios/dist/node/axios.cjs:1859:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@1.2.2/node_modules/axios/dist/node/axios.cjs:2723:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]} +45ms
backend_1  | [Wisdom] Error     Sat, 14 Jan 2023 16:01:10 GMT [ExceptionsHandler] Request failed with status code 429 - {"stack":["AxiosError: Request failed with status code 429\n    at settle (/app/node_modules/.pnpm/axios@1.2.2/node_modules/axios/dist/node/axios.cjs:1859:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@1.2.2/node_modules/axios/dist/node/axios.cjs:2723:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]} +12ms
backend_1  | [Wisdom] Error     Sat, 14 Jan 2023 16:01:10 GMT [ExceptionsHandler] Request failed with status code 429 - {"stack":["AxiosError: Request failed with status code 429\n    at settle (/app/node_modules/.pnpm/axios@1.2.2/node_modules/axios/dist/node/axios.cjs:1859:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@1.2.2/node_modules/axios/dist/node/axios.cjs:2723:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]} +140ms
backend_1  | [Wisdom] Error     Sat, 14 Jan 2023 16:06:05 GMT [ExceptionsHandler] Request failed with status code 429 - {"stack":["AxiosError: Request failed with status code 429\n    at settle (/app/node_modules/.pnpm/axios@1.2.2/node_modules/axios/dist/node/axios.cjs:1859:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@1.2.2/node_modules/axios/dist/node/axios.cjs:2723:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]} +5m
```

**Comment by jonfelixrico** [comment]
Fix verified to be working with the same quote preview which triggered these errors in the BE. FE looks fine too.
